
services:
  db:
    image: postgres:15
    container_name: rental_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rental_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: rental_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/rental_db
      NODE_ENV: development
      PORT: 5000
    depends_on:
      - db

volumes:
  postgres_data:
